# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81315534c86396ac1de90012efad79cb5e3fd51d507775ca07b5570fbaf19782dab8758c409aee8818903ccf5f43790a1d631c2fe8b66b9efad63a6f7ecf220

test:
  secret_key_base: c6381c144ccf8ab4e9f0a13705fedf5f909b36e416a85966a35da6749779c6940768d32e050188ddb62c0e514065aa92fbf1f3ecacbec846739c11df04bbf0e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
